FROM nginx:alpine
COPY ui/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Nginx default configuration automatically serves static files from this dir on port 80.
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
