services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: [ "sh", "-c", "ollama serve & sleep 5 && ollama pull qwen2.5 && ollama pull qwen3:4b && ollama pull nomic-embed-text && wait" ]
