# ui/app.py
# Streamlit chat frontend for the document assistant.
# Talks to the FastAPI backend over HTTP — doesn't touch FAISS or Ollama directly.
#
# Features:
#   - Persistent conversation history with session switching
#   - Document library with per-document management
#   - Model selection with descriptions
#   - Document filtering for targeted questions
#   - Stop generation button
#
# To run:  python -m streamlit run ui/app.py
# (make sure the backend is already running on port 8000)

import os
import streamlit as st
import requests

API_URL = os.getenv("API_URL", "http://localhost:8000")


# -- helpers -----------------------------------------------------------------

def api_get(path: str, timeout: int = 5):
    """GET helper that returns JSON or None on failure."""
    try:
        resp = requests.get(f"{API_URL}{path}", timeout=timeout)
        if resp.status_code == 200:
            return resp.json()
    except (requests.ConnectionError, requests.exceptions.ReadTimeout):
        pass
    return None


def api_post(path: str, json=None, timeout: int = 10):
    """POST helper that returns (status_code, json_or_text)."""
    try:
        resp = requests.post(f"{API_URL}{path}", json=json, timeout=timeout)
        try:
            return resp.status_code, resp.json()
        except requests.exceptions.JSONDecodeError:
            return resp.status_code, resp.text
    except requests.ConnectionError:
        return None, "Could not reach the API."
    except requests.exceptions.ReadTimeout:
        return None, "Request timed out."


def api_delete(path: str, timeout: int = 10):
    """DELETE helper that returns (status_code, json_or_text)."""
    try:
        resp = requests.delete(f"{API_URL}{path}", timeout=timeout)
        try:
            return resp.status_code, resp.json()
        except requests.exceptions.JSONDecodeError:
            return resp.status_code, resp.text
    except requests.ConnectionError:
        return None, "Could not reach the API."


# -- page setup --------------------------------------------------------------

st.set_page_config(page_title="AI Document Assistant", layout="wide")

st.title("AI Document Assistant")
st.markdown(
    "Upload documents (PDF, TXT, DOCX, MD, HTML), then ask natural-language "
    "questions about their content. Answers are generated by a local LLM "
    "using Retrieval-Augmented Generation. **All data stays on your machine.**"
)

# -- session state initialization --------------------------------------------

if "current_conversation_id" not in st.session_state:
    st.session_state.current_conversation_id = None
if "messages" not in st.session_state:
    st.session_state.messages = []


# -- sidebar -----------------------------------------------------------------

with st.sidebar:

    # ---- Conversations Panel -----------------------------------------------
    st.header("💬 Conversations")

    # new conversation button
    if st.button("✨ New Conversation", use_container_width=True, type="primary"):
        st.session_state.current_conversation_id = None
        st.session_state.messages = []
        st.rerun()

    # fetch conversations from backend
    conversations = api_get("/conversations") or []

    if conversations:
        for c in conversations:
            conv_id = c["conversation_id"]
            is_active = conv_id == st.session_state.current_conversation_id

            col1, col2 = st.columns([5, 1])
            with col1:
                label = f"{'▶ ' if is_active else ''}{c['title']}"
                if st.button(
                    label,
                    key=f"conv_{conv_id}",
                    use_container_width=True,
                    type="primary" if is_active else "secondary",
                ):
                    # load this conversation
                    st.session_state.current_conversation_id = conv_id
                    detail = api_get(f"/conversations/{conv_id}")
                    if detail and detail.get("messages"):
                        st.session_state.messages = [
                            {
                                "role": m["role"],
                                "content": m["content"],
                                "context": m.get("context_chunks", []),
                            }
                            for m in detail["messages"]
                        ]
                    else:
                        st.session_state.messages = []
                    st.rerun()
            with col2:
                if st.button("🗑️", key=f"delconv_{conv_id}", help="Delete conversation"):
                    status, _ = api_delete(f"/conversations/{conv_id}")
                    if status == 200:
                        # if we deleted the active conversation, reset
                        if conv_id == st.session_state.current_conversation_id:
                            st.session_state.current_conversation_id = None
                            st.session_state.messages = []
                        st.rerun()
    else:
        st.caption("No conversations yet. Ask a question to start one!")

    st.divider()

    # ---- AI Model Selection ------------------------------------------------
    st.header("🤖 AI Model")
    available_models = ["qwen2.5:latest"]
    fetched = api_get("/models")
    if fetched:
        available_models = fetched

    MODEL_INFO = {
        "qwen2.5:latest": "Best overall — strong reasoning & multilingual (recommended)",
        "qwen3:4b": "Lightweight — fast but limited analysis",
        "qwen2.5:7b": "Larger variant — strongest reasoning (needs more VRAM)",
        "llama3.2:latest": "Meta's general-purpose model",
        "mistral:latest": "Fast European multilingual model",
    }

    # try to default to qwen2.5 if available
    default_idx = 0
    for i, m in enumerate(available_models):
        if "qwen2.5" in m:
            default_idx = i
            break

    selected_model = st.selectbox(
        "Select Model",
        options=available_models,
        index=default_idx,
        format_func=lambda m: f"{m}  —  {MODEL_INFO[m]}" if m in MODEL_INFO else m,
        help="Choose which AI model answers your questions.",
    )
    st.divider()

    # ---- Document Upload ---------------------------------------------------
    st.header("📄 Document Upload")

    uploaded_file = st.file_uploader(
        "Choose a document",
        type=["pdf", "txt", "docx", "md", "html"],
        help="Supported formats: PDF, TXT, DOCX, MD, HTML",
    )

    if uploaded_file and st.button("Ingest Document", use_container_width=True):
        with st.spinner("Processing document..."):
            try:
                files = {
                    "file": (
                        uploaded_file.name,
                        uploaded_file.getvalue(),
                        uploaded_file.type,
                    )
                }
                resp = requests.post(f"{API_URL}/upload", files=files, timeout=300)
                if resp.status_code == 200:
                    data = resp.json()
                    st.success(
                        f"**{data['filename']}** ingested successfully.\n\n"
                        f"Chunks added: {data['chunks_added']}\n\n"
                        f"Total chunks in store: {data['total_chunks']}"
                    )
                elif resp.status_code == 409:
                    detail = resp.json().get("detail", "Duplicate file.")
                    st.warning(f"⚠️ {detail}")
                else:
                    st.error(f"Error: {resp.json().get('detail', resp.text)}")
            except requests.exceptions.ReadTimeout:
                st.error(
                    "The request timed out. If you are running on a CPU, "
                    "processing large documents can take several minutes."
                )
            except requests.ConnectionError:
                st.error(
                    "Could not reach the API. "
                    "Make sure the FastAPI server is running on port 8000."
                )

    st.divider()

    # ---- Document Library --------------------------------------------------
    st.header("📚 Document Library")

    documents = api_get("/documents") or []

    if documents:
        doc_options = {d["original_name"]: d["doc_id"] for d in documents}

        selected_doc_names = st.multiselect(
            "Filter by document",
            options=list(doc_options.keys()),
            help="Leave empty to search all documents, or select specific ones.",
        )
        selected_doc_ids = (
            [doc_options[name] for name in selected_doc_names]
            if selected_doc_names
            else None
        )

        st.caption(f"**{len(documents)}** document(s) in library")

        for doc in documents:
            with st.container():
                col1, col2 = st.columns([4, 1])
                with col1:
                    size_kb = doc["file_size"] / 1024
                    st.markdown(
                        f"**{doc['original_name']}**  \n"
                        f"`{doc['file_type']}` · {size_kb:.1f} KB · "
                        f"{doc['chunk_count']} chunks"
                    )
                with col2:
                    if st.button("🗑️", key=f"del_{doc['doc_id']}", help="Delete this document"):
                        status, _ = api_delete(f"/documents/{doc['doc_id']}")
                        if status == 200:
                            st.success(f"Deleted {doc['original_name']}")
                            st.rerun()
                        else:
                            st.error("Failed to delete document.")
                st.divider()
    else:
        selected_doc_ids = None
        st.info("No documents uploaded yet.")

    # ---- Store Status & Clear ----------------------------------------------
    st.header("🔧 Maintenance")

    col_a, col_b = st.columns(2)
    with col_a:
        if st.button("Refresh Status", use_container_width=True):
            data = api_get("/status")
            if data:
                st.metric("Total Chunks", data["total_chunks"])
                st.info(f"Status: **{data['status']}**")
            else:
                st.error("API not reachable.")
    with col_b:
        if st.button("Clear All", use_container_width=True, type="secondary"):
            status, _ = api_post("/clear")
            if status == 200:
                st.session_state.current_conversation_id = None
                st.session_state.messages = []
                st.success("All data cleared.")
                st.rerun()
            else:
                st.error("API not reachable.")


# -- main area: the chat interface -------------------------------------------

st.header("Question & Answer")

# show current conversation indicator
if st.session_state.current_conversation_id:
    # find the title from the conversations list
    conv_title = None
    for c in conversations:
        if c["conversation_id"] == st.session_state.current_conversation_id:
            conv_title = c["title"]
            break
    if conv_title:
        st.caption(f"📝 Conversation: **{conv_title}**")
else:
    st.caption("📝 *New conversation — your first question will start it.*")

# show old messages
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("context"):
            with st.expander("Retrieved context"):
                for i, chunk in enumerate(msg["context"], 1):
                    st.markdown(f"**Chunk {i}:**\n{chunk}")
                    st.divider()

# handle new questions
if question := st.chat_input("Ask something about your documents..."):
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):
        # stop button
        stop_placeholder = st.empty()
        stop_clicked = stop_placeholder.button(
            "⏹ Stop generating", type="secondary", use_container_width=True,
        )

        if stop_clicked:
            stop_placeholder.empty()
            st.warning("Generation cancelled.")
            st.session_state.messages.append({
                "role": "assistant",
                "content": "*(Generation cancelled by user)*",
                "context": [],
            })
        else:
            with st.spinner("Generating answer..."):
                try:
                    payload = {
                        "question": question,
                        "model": selected_model,
                    }
                    # attach to current conversation if one exists
                    if st.session_state.current_conversation_id:
                        payload["conversation_id"] = st.session_state.current_conversation_id
                    # only add doc_ids filter if user selected specific documents
                    if selected_doc_ids:
                        payload["doc_ids"] = selected_doc_ids

                    resp = requests.post(
                        f"{API_URL}/ask",
                        json=payload,
                        timeout=600,
                    )
                    stop_placeholder.empty()

                    if resp.status_code == 200:
                        data = resp.json()
                        answer = data["answer"]

                        # track the conversation ID (new or existing)
                        if data.get("conversation_id"):
                            st.session_state.current_conversation_id = data["conversation_id"]

                        st.markdown(answer)
                        if data.get("context_chunks"):
                            with st.expander("Retrieved context"):
                                for i, chunk in enumerate(data["context_chunks"], 1):
                                    st.markdown(f"**Chunk {i}:**\n{chunk}")
                                    st.divider()
                        st.session_state.messages.append({
                            "role": "assistant",
                            "content": answer,
                            "context": data.get("context_chunks", []),
                        })
                    else:
                        try:
                            err = resp.json().get("detail", resp.text)
                        except requests.exceptions.JSONDecodeError:
                            err = resp.text or f"Server error (status {resp.status_code})"
                        st.error(f"Error: {err}")
                except requests.exceptions.ReadTimeout:
                    stop_placeholder.empty()
                    st.error(
                        "The model took too long to respond (timeout). "
                        "Try asking a simpler question, or run in GPU mode."
                    )
                except requests.ConnectionError:
                    stop_placeholder.empty()
                    st.error(
                        "Could not reach the API. Make sure the FastAPI server "
                        "is running: python -m uvicorn app.main:app --port 8000"
                    )
