# ui/app.py
# Streamlit chat frontend for the document assistant.
# Talks to the FastAPI backend over HTTP -- doesn't touch FAISS or Ollama directly.
#
# To run:  python -m streamlit run ui/app.py
# (make sure the backend is already running on port 8000)

import os
import streamlit as st
import requests

API_URL = os.getenv("API_URL", "http://localhost:8000")

# -- page setup --

st.set_page_config(page_title="AI Document Assistant", layout="wide")

st.title("AI Document Assistant")
st.markdown(
    "Upload documents (PDF, TXT, DOCX, MD, HTML), then ask natural-language questions "
    "about their content.  Answers are generated by a local LLM using "
    "Retrieval-Augmented Generation.  **All data stays on your machine.**"
)

# -- sidebar: model selection, file upload, document library --

with st.sidebar:

    # ---- AI Model Selection ------------------------------------------------
    st.header("AI Model")
    available_models = ["qwen3:4b"]
    try:
        m_resp = requests.get(f"{API_URL}/models", timeout=5)
        if m_resp.status_code == 200:
            fetched = m_resp.json()
            if fetched:
                available_models = fetched
    except requests.ConnectionError:
        pass

    # model descriptions to help users pick the right one
    MODEL_INFO = {
        "qwen3:4b": "Fast, lightweight (recommended for most use)",
        "qwen2.5:latest": "Strong multilingual & Arabic support",
        "qwen2.5:7b": "Strong multilingual & Arabic support (7B)",
        "llama3.2:latest": "Meta's general-purpose model",
        "mistral:latest": "Fast European multilingual model",
    }

    selected_model = st.selectbox(
        "Select Model",
        options=available_models,
        index=0,
        format_func=lambda m: f"{m}  —  {MODEL_INFO[m]}" if m in MODEL_INFO else m,
        help="Choose which AI model answers your questions. Embedding models are filtered out automatically.",
    )
    st.divider()

    # ---- Document Upload ---------------------------------------------------
    st.header("Document Upload")

    uploaded_file = st.file_uploader(
        "Choose a document",
        type=["pdf", "txt", "docx", "md", "html"],
        help="Supported formats: PDF, TXT, DOCX, MD, HTML",
    )

    if uploaded_file and st.button("Ingest Document", use_container_width=True):
        with st.spinner("Processing document..."):
            try:
                files = {
                    "file": (
                        uploaded_file.name,
                        uploaded_file.getvalue(),
                        uploaded_file.type,
                    )
                }
                resp = requests.post(f"{API_URL}/upload", files=files, timeout=300)
                if resp.status_code == 200:
                    data = resp.json()
                    st.success(
                        f"**{data['filename']}** ingested successfully.\n\n"
                        f"Chunks added: {data['chunks_added']}\n\n"
                        f"Total chunks in store: {data['total_chunks']}"
                    )
                elif resp.status_code == 409:
                    # duplicate file detected
                    detail = resp.json().get("detail", "Duplicate file.")
                    st.warning(f"⚠️ {detail}")
                else:
                    st.error(f"Error: {resp.json().get('detail', resp.text)}")
            except requests.exceptions.ReadTimeout:
                st.error(
                    "The request timed out. If you are running on a CPU, "
                    "processing large documents can take several minutes."
                )
            except requests.ConnectionError:
                st.error(
                    "Could not reach the API. "
                    "Make sure the FastAPI server is running on port 8000."
                )

    st.divider()

    # ---- Document Library --------------------------------------------------
    st.header("Document Library")

    # fetch documents from the backend
    documents = []
    try:
        doc_resp = requests.get(f"{API_URL}/documents", timeout=5)
        if doc_resp.status_code == 200:
            documents = doc_resp.json()
    except requests.ConnectionError:
        pass

    if documents:
        # document filter: let users pick which documents to search
        doc_options = {d["original_name"]: d["doc_id"] for d in documents}

        selected_doc_names = st.multiselect(
            "Filter by document",
            options=list(doc_options.keys()),
            help="Leave empty to search all documents, or select specific ones.",
        )
        selected_doc_ids = (
            [doc_options[name] for name in selected_doc_names]
            if selected_doc_names
            else None
        )

        st.caption(f"**{len(documents)}** document(s) in library")

        for doc in documents:
            with st.container():
                col1, col2 = st.columns([4, 1])
                with col1:
                    size_kb = doc["file_size"] / 1024
                    st.markdown(
                        f"**{doc['original_name']}**  \n"
                        f"`{doc['file_type']}` · {size_kb:.1f} KB · "
                        f"{doc['chunk_count']} chunks"
                    )
                with col2:
                    if st.button("🗑️", key=f"del_{doc['doc_id']}", help="Delete this document"):
                        try:
                            del_resp = requests.delete(
                                f"{API_URL}/documents/{doc['doc_id']}", timeout=10,
                            )
                            if del_resp.status_code == 200:
                                st.success(f"Deleted {doc['original_name']}")
                                st.rerun()
                            else:
                                st.error("Failed to delete document.")
                        except requests.ConnectionError:
                            st.error("API not reachable.")
                st.divider()
    else:
        selected_doc_ids = None
        st.info("No documents uploaded yet.")

    # ---- Store Status & Clear ----------------------------------------------
    st.header("Vector Store")
    if st.button("Refresh Status", use_container_width=True):
        try:
            resp = requests.get(f"{API_URL}/status", timeout=10)
            if resp.status_code == 200:
                data = resp.json()
                st.metric("Total Chunks", data["total_chunks"])
                st.info(f"Status: **{data['status']}**")
        except requests.ConnectionError:
            st.error("API not reachable.")

    st.divider()

    if st.button("Clear All Documents", use_container_width=True, type="secondary"):
        try:
            resp = requests.post(f"{API_URL}/clear", timeout=10)
            if resp.status_code == 200:
                st.success("All documents and embeddings cleared.")
                st.rerun()
        except requests.ConnectionError:
            st.error("API not reachable.")

# -- main area: the chat interface --

st.header("Question & Answer")

# keep the conversation in session state so it sticks around between reruns
if "messages" not in st.session_state:
    st.session_state.messages = []

# show old messages
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("context"):
            with st.expander("Retrieved context"):
                for i, chunk in enumerate(msg["context"], 1):
                    st.markdown(f"**Chunk {i}:**\n{chunk}")
                    st.divider()

# handle new questions
if question := st.chat_input("Ask something about your documents..."):
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):
        with st.spinner("Generating answer..."):
            try:
                payload = {
                    "question": question,
                    "model": selected_model,
                }
                # only add doc_ids filter if user selected specific documents
                if selected_doc_ids:
                    payload["doc_ids"] = selected_doc_ids

                resp = requests.post(
                    f"{API_URL}/ask",
                    json=payload,
                    timeout=600,
                )
                if resp.status_code == 200:
                    data = resp.json()
                    st.markdown(data["answer"])
                    if data.get("context_chunks"):
                        with st.expander("Retrieved context"):
                            for i, chunk in enumerate(data["context_chunks"], 1):
                                st.markdown(f"**Chunk {i}:**\n{chunk}")
                                st.divider()
                    st.session_state.messages.append({
                        "role": "assistant",
                        "content": data["answer"],
                        "context": data.get("context_chunks", []),
                    })
                else:
                    try:
                        err = resp.json().get("detail", resp.text)
                    except requests.exceptions.JSONDecodeError:
                        err = resp.text or f"Server error (status {resp.status_code})"
                    st.error(f"Error: {err}")
            except requests.exceptions.ReadTimeout:
                st.error(
                    "The model took too long to respond (timeout). Running AI models on a CPU can be slow. "
                    "Try asking a simpler question, or run the application in GPU mode if you have an NVIDIA graphics card."
                )
            except requests.ConnectionError:
                st.error(
                    "Could not reach the API. Make sure the FastAPI server "
                    "is running:  python -m uvicorn app.main:app --port 8000"
                )
