# ui/app.py
# Streamlit chat frontend for the document assistant.
# Talks to the FastAPI backend over HTTP -- doesn't touch FAISS or Ollama directly.
#
# To run:  python -m streamlit run ui/app.py
# (make sure the backend is already running on port 8000)

import os
import streamlit as st
import requests

API_URL = os.getenv("API_URL", "http://localhost:8000")

# -- page setup --

st.set_page_config(page_title="AI Document Assistant", layout="wide")

st.title("AI Document Assistant")
st.markdown(
    "Upload documents (PDF, TXT, DOCX, MD, HTML), then ask natural-language questions "
    "about their content.  Answers are generated by a local LLM using "
    "Retrieval-Augmented Generation."
)

# -- sidebar: file upload, store status, clear button --

with st.sidebar:
    st.header("Document Upload")

    uploaded_file = st.file_uploader(
        "Choose a document",
        type=["pdf", "txt", "docx", "md", "html"],
        help="Supported formats: PDF, TXT, DOCX, MD, HTML",
    )

    if uploaded_file and st.button("Ingest Document", use_container_width=True):
        with st.spinner("Processing document..."):
            try:
                files = {
                    "file": (
                        uploaded_file.name,
                        uploaded_file.getvalue(),
                        uploaded_file.type,
                    )
                }
                resp = requests.post(f"{API_URL}/upload", files=files, timeout=300)
                if resp.status_code == 200:
                    data = resp.json()
                    st.success(
                        f"**{data['filename']}** ingested successfully.\n\n"
                        f"Chunks added: {data['chunks_added']}\n\n"
                        f"Total chunks in store: {data['total_chunks']}"
                    )
                else:
                    st.error(f"Error: {resp.json().get('detail', resp.text)}")
            except requests.ConnectionError:
                st.error(
                    "Could not reach the API. "
                    "Make sure the FastAPI server is running on port 8000."
                )

    st.divider()

    st.header("Vector Store")
    if st.button("Refresh Status", use_container_width=True):
        try:
            resp = requests.get(f"{API_URL}/status", timeout=10)
            if resp.status_code == 200:
                data = resp.json()
                st.metric("Total Chunks", data["total_chunks"])
                st.info(f"Status: **{data['status']}**")
        except requests.ConnectionError:
            st.error("API not reachable.")

    st.divider()

    if st.button("Clear All Documents", use_container_width=True):
        try:
            resp = requests.post(f"{API_URL}/clear", timeout=10)
            if resp.status_code == 200:
                st.success("All documents and embeddings cleared.")
        except requests.ConnectionError:
            st.error("API not reachable.")

# -- main area: the chat interface --

st.header("Question & Answer")

# keep the conversation in session state so it sticks around between reruns
if "messages" not in st.session_state:
    st.session_state.messages = []

# show old messages
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("context"):
            with st.expander("Retrieved context"):
                for i, chunk in enumerate(msg["context"], 1):
                    st.markdown(f"**Chunk {i}:**\n{chunk}")
                    st.divider()

# handle new questions
if question := st.chat_input("Ask something about your documents..."):
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):
        with st.spinner("Generating answer..."):
            try:
                resp = requests.post(
                    f"{API_URL}/ask",
                    json={"question": question},
                    timeout=120,
                )
                if resp.status_code == 200:
                    data = resp.json()
                    st.markdown(data["answer"])
                    if data.get("context_chunks"):
                        with st.expander("Retrieved context"):
                            for i, chunk in enumerate(data["context_chunks"], 1):
                                st.markdown(f"**Chunk {i}:**\n{chunk}")
                                st.divider()
                    st.session_state.messages.append({
                        "role": "assistant",
                        "content": data["answer"],
                        "context": data.get("context_chunks", []),
                    })
                else:
                    err = resp.json().get("detail", resp.text)
                    st.error(f"Error: {err}")
            except requests.ConnectionError:
                st.error(
                    "Could not reach the API. Make sure the FastAPI server "
                    "is running:  python -m uvicorn app.main:app --port 8000"
                )
